set tabstop=2       " The width of a TAB is set to 2.
                    " Still it is a \t. It is just that
                    " Vim will interpret it to be having
                    " a width of 2.

set shiftwidth=2    " Indents will have a width of 2, size of an "indent"

set softtabstop=2   " Sets the number of columns for a TAB
                    " a combination of spaces and tabs are used to simulate tab stops at a width
                    " other than the (hard)tabstop

set expandtab       " always uses spaces instead of tab characters

set smarttab	    " make "tab" insert indents instead of tabs at the beginning of a line

" activates filetype detection
filetype plugin indent on

" activates syntax highlighting among other things
syntax on

" allows you to deal with multiple unsaved
" buffers simultaneously without resorting
" to misusing tabs
"set hidden

" just hit backspace without this one and
" see for yourself
"set backspace=indent,eol,start

